### ISSUE TITLE
Upgrade to de.flapdoodle.embed.mongo 3.0.0

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-mongodb#125]

**Comment by graemerocher** [comment]
Personally I think it is should be deprecated in favour for test containers

**Comment by alvarosanchez** [comment]
I wasn't clear about how `MongoProcessFactory` was used in other projects, so I created this issue to not forget about it, just in case.

But you are right, also we are already standardising around TC containers in other places. Closing this.
