### ISSUE TITLE
Embedded mongo replica set

### ISSUE THREAD

**Issue by finke-ba** [micronaut-projects/micronaut-mongodb#13]
Hi @graemerocher!

I figured out that there is no possibility to run embedded mongodb in replica set mode.
I assume to add this logic to `AbstractMongoProcessFactory`.
Probably we could use already existing `ClusterSettings` - `ClusterConnectionMode mode` and `String requiredReplicaSetName` for this if these fields are already mapped with application properties file - `mongodb.cluster.mode` and `mongodb.cluster.requiredReplicaSetName`.
How does that sound to you?

**Comment by graemerocher** [comment]
Seems reasonable to me

**Comment by finke-ba** [comment]
Does ClusterSettings already mapped with application properties file?

**Comment by graemerocher** [comment]
Yes under `cluster`. See https://github.com/micronaut-projects/micronaut-mongodb/blob/master/mongo-reactive/src/main/java/io/micronaut/configuration/mongo/reactive/DefaultReactiveMongoConfiguration.java#L53
