### ISSUE TITLE
insertOne does not return ObjectId

### ISSUE THREAD

**Issue by kamilgregorczyk** [micronaut-projects/micronaut-mongodb#2]
Statement:
```
mongoClient
        .getDatabase(DATABASE)
        .getCollection(COLLECTION, Article.class)
        .insertOne(article);
```
`insertOne` returns a publisher which only tells whether the save action was successful or not, it could (and I think it should) also return ObjectId so that it could be easier to create and then retrieve that object from db.

mongo client returns ObjectId:
```
> db.posts.insertOne({a:1})
{
	"acknowledged" : true,
	"insertedId" : ObjectId("5c5f1c814c95415415c0b8d7")
}
>
```

**Comment by graemerocher** [comment]
This has little to do with Micronaut and relates to the API of the driver which is beyond our control
