### ISSUE TITLE
Blocking MongoClient comes with no pojo codec configuration

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-mongodb#22]
Injected `com.mongodb.MongoClient` comes with no pojo codec configuration, what results in `Can't find a codec for class [...]` after the first usage.

Additionally, `DefaultMongoClientFactory` comes with old `com.mongodb.MongoClient`, while the new one is `com.mongodb.client.MongoClient`. I believe the default implementation should be changed to the latter one with a configuration exactly compatible with the one used for the reactive client:

```java
public class DefaultMongoClientFactory {

	@Bean(preDestroy = "close")
	@Primary
	@Singleton
	public com.mongodb.client.MongoClient mongoClient(DefaultReactiveMongoConfiguration configuration) {
		return MongoClients.create(configuration.buildSettings());
	}

}
```

**Comment by graemerocher** [comment]
Yes it does need to change though that is a breaking change and would need a new major version

**Comment by l0co** [comment]
Indeed. However, you could also provide the new bean along with the old one, what is not a breaking change, and will allow people to migrate over time.

Unless the old bean eats some resources, like connections, threads... I haven't looked at this.

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-mongodb/commit/a2a70401b0778c0b3a1be172879fcf78b7cc3a61
