### ISSUE TITLE
Password is not masked in /env 

### ISSUE THREAD

**Issue by vainikkaj** [micronaut-projects/micronaut-mongodb#224]
### Expected Behavior

After adding micronaut-mongodb into project, I expected there to be way to configure password without showing it in `/env` monitoring endpoint.

### Actual Behaviour

It seems that only way to configure password is to use `mongodb.uri` configuration which does not match [masked property names](https://github.com/micronaut-projects/micronaut-core/blob/3.0.x/management/src/main/java/io/micronaut/management/endpoint/env/EnvironmentEndpoint.java#L49)

### Version

2.4.1

**Comment by graemerocher** [comment]
Fixed in core with https://github.com/micronaut-projects/micronaut-core/pull/6711
