### ISSUE TITLE
Inserting POJO using mongo-reactive doesn't set the id

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-mongodb#251]
According to [quick-start-pojo](http://mongodb.github.io/mongo-java-driver/3.8/driver/getting-started/quick-start-pojo/) and [bson-pojos](http://mongodb.github.io/mongo-java-driver/3.8/bson/pojos/) to automatically convert mongo documents to POJOs we need to:
- Register a PojoCodecProvider. Done here: https://github.com/micronaut-projects/micronaut-core/blob/e97b8e0759231765ceb07d75eb100edce5fbf51a/configurations/mongo-reactive/src/main/java/io/micronaut/configuration/mongo/reactive/AbstractReactiveMongoConfiguration.java#L148-L152
- Have an empty constructor in the POJO class

This test https://github.com/micronaut-projects/micronaut-core/commit/0eb8a40ad195d8c63823e658779553f6ff1c0cff in the brach `mongo-reactive-insert-pojo`  fails because the `id` is not set after saving the object in mongo. I can see that the `_id` field is generated in mongo but it is always `null` in the instance. 

I'm not really sure if we need to configure anything else on Micronaut or maybe I'm missing something in my example.

I've also tried defining the `id` property as `String` and also annotate it with `@BsonId` but the result is the same.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** Micronaut.1.0.0.RC1
- **JDK Version:** openjdk version "1.8.0_181"

**Comment by timyates** [comment]
I couldn't reproduce the original issue here, I have merged in a test to ensure we don't get a regression

https://github.com/micronaut-projects/micronaut-mongodb/pull/250

Please raise a fresh issue if you still encounter issues
