### ISSUE TITLE
Automatic timestamping and versioning not working

### ISSUE THREAD

**Issue by thwuersch** [micronaut-projects/micronaut-mongodb#3]
With version 1.1.0.RC1 automatic updates of version, dateCreated and lastUpdated fields in Entity objects worked. With version 1.1.0.RC2 and 1.1.0 these fields remain null.

**Comment by ilopmar** [comment]
Can you please provide a sample application?

**Comment by thwuersch** [comment]
Im using Micronaut 1.1.0

My build.gradle:

`plugins {
    id "io.spring.dependency-management" version "1.0.6.RELEASE"
    id "groovy"
    id "com.github.johnrengelman.shadow" version "4.0.2"
    id "application"
}



version "0.1"
group "ch.twinf"

repositories {
    mavenCentral()
    maven { url "https://jcenter.bintray.com" }
}

dependencyManagement {
    imports {
        mavenBom 'io.micronaut:micronaut-bom:1.1.0'
    }
}

configurations {
    // for dependencies that are needed for development only
    developmentOnly 
}

dependencies {
    compile "io.micronaut:micronaut-runtime-groovy"
    compile "io.micronaut:micronaut-validation"
    compile "io.micronaut.configuration:micronaut-mongo-reactive"
    compile "io.micronaut:micronaut-http-client"
    compile "io.micronaut.configuration:micronaut-mongo-gorm"
    compile "io.micronaut:micronaut-http-server-netty"
    compileOnly "io.micronaut:micronaut-inject-groovy"
    runtime "ch.qos.logback:logback-classic:1.2.3"
    testAnnotationProcessor "io.micronaut:micronaut-inject-java"
    testCompile("org.spockframework:spock-core") {
        exclude group: "org.codehaus.groovy", module: "groovy-all"
    }
    testCompile "io.micronaut:micronaut-inject-groovy"
    testCompile "io.micronaut.test:micronaut-test-spock:1.0.1"
    testCompile "org.junit.jupiter:junit-jupiter-api"
    testCompile "io.micronaut.test:micronaut-test-junit5"
    testRuntime "org.junit.jupiter:junit-jupiter-engine"
}

test.classpath += configurations.developmentOnly

mainClassName = "ch.twinf.Application"

// use JUnit 5 platform
test {
    useJUnitPlatform()
}

tasks.withType(GroovyCompile) {
    groovyOptions.forkOptions.jvmArgs.add('-Dgroovy.parameters=true')
}


shadowJar {
    mergeServiceFiles()
}

run.classpath += configurations.developmentOnly
run.jvmArgs('-noverify', '-XX:TieredStopAtLevel=1', '-Dcom.sun.management.jmxremote')
`
The entity is:

`@Entity
class User implements GormEntity<User> {

    String id

    Long version
    Date dateCreated
    Date lastUpdated

    String username
    String password

}`

and the Spec:

`@MicronautTest(application = Application)
class UserSpec extends Specification {

    @Shared
    boolean isReady = false

    void setup() {
        if (!isReady) {
            User.deleteAll(User.findAll())
            isReady = true
        }
    }

    def 'insert does not initialize version, dateCreated and lastUpdated'() {
        given:
        new User(
                id: UUID.randomUUID().toString(),
                username: 'user1',
                password: 'pwd1'
        ).insert([flush: true, failOnError: true])

        when:
        def user = User.findAll()[0]

        then:
        user.version == null
        user.dateCreated == null
        user.lastUpdated == null
    }

    def 'save does not update version and lastUpdated'() {
        given:
        def user = User.findByUsername('user1')

        expect:
        user.username == 'user1'

        when:
        user.password = 'pwd99'
        user = user.save([flush: true, failOnError: true])

        then:
        user.version == null
        user.dateCreated == null
        user.lastUpdated == null
    }

}`

The second test produces an Exception:

`org.grails.datastore.mapping.core.OptimisticLockingException: The instance was updated by another user while you were editing

	at org.grails.datastore.mapping.mongo.MongoCodecSession.flush(MongoCodecSession.groovy:249)
	at org.grails.datastore.mapping.mongo.AbstractMongoSession.flush(AbstractMongoSession.java:74)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:368)
	at org.grails.datastore.gorm.GormInstanceApi.save_closure5(GormInstanceApi.groovy:180)
	at groovy.lang.Closure.call(Closure.java:405)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:179)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:153)
	at ch.twinf.UserSpec.save does not update version and lastUpdated(UserSpec.groovy:65)`


[gorm.zip](https://github.com/micronaut-projects/micronaut-mongodb/files/3106080/gorm.zip)

**Comment by graemerocher** [comment]
This is the same as https://github.com/micronaut-projects/micronaut-core/issues/1538

**Comment by thwuersch** [comment]
Sorry, have not seen this issue. Thanks.
