### ISSUE TITLE
Codecs for Enum values stopped working with Micronaut 3.5.1

### ISSUE THREAD

**Issue by ckosmowski** [micronaut-projects/micronaut-mongodb#323]
### Expected Behavior

Beans of the type Codec<T> are used to encode and decode values when read / written by the mongodb integration.

### Actual Behaviour

Most of the Codecs still work as before but Codecs of Enum Types are no longer used to decode.

### Steps To Reproduce

Create a Document to write to / read from the mongodb
Make one of the fields of that document a property of a Java Enum
Create a Codec for that Type

With Micronaut 3.4.4 the Codec is picked up and used to decode the property
With Micronaut 3.5.1 (no other changes) the Codec is not called anymore

### Environment Information

JDK 17
Micronaut 3.4.4 / 3.5.1

### Version

3.5.1

**Comment by dstepanov** [comment]
I think this will be fixed by https://github.com/micronaut-projects/micronaut-mongodb/pull/320

**Comment by dstepanov** [comment]
Should be fixed by the PR mentioned
