### ISSUE TITLE
Remove flapdoodle from module and update docs.

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-mongodb#386]
### Issue description

PR #306 migrates flapdoodle from v2 to v4 (it has breaking API changes). 

The docs recommend using Testcontainers for testing, and say that flapdoodle can be used as an alternative. The module includes the `MongoProcessFactory` class to support flapdoodle for testing.

We should consider just removing flapdoodle altogether for Micronaut 4. It is not needed.

@sdelamo if you agree, assign this to me and I can take care of it.

**Comment by sdelamo** [comment]
@micronaut-projects/core-developers what do you think?

I don't have any experience with flapdoodle. But if it is possible to test with Testcontainers my vote is to remove flapdoodle support and it is one thing less to support.

**Comment by alvarosanchez** [comment]
@wetted go ahead and remove it
