### ISSUE TITLE
How to save a document in mongo with indexed attribute?

### ISSUE THREAD

**Issue by mateuslima90** [micronaut-projects/micronaut-mongodb#41]
Hi, 

It is possible to save document in mongodb with indexed unique attribute?

The idea is same a spring-data-mongodb

```
@Document
public class User {
    @Id
    private String id;
    @Indexed (unique = true)
    private String name;
    private String password;
    ... 
}
```
thanks

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](https://stackoverflow.com/questions/tagged/micronaut).

You can also try with asking in [Gitter](https://gitter.im/micronautfw/).
