### ISSUE TITLE
Provide a more complete example of how to use Test Containers

### ISSUE THREAD

**Issue by ajarosz** [micronaut-projects/micronaut-mongodb#72]
Hello everyone. 
In my project I'm using mongodb plugin. I have my mongo configuration defined in application.yml. According to the documentation the suggested way of testing the integration with mongo is to use [testcontainers](https://www.testcontainers.org/) which spins up dockerized mongo instance. Now the problem is testcontainers exposes the mongo instance on a random port which can be only known at runtime. How can I override my mongo config defined in application.yml and inject new connection string? 

EDIT:
I achieved it by implementing TestPropertyProvider described [here](https://micronaut-projects.github.io/micronaut-test/latest/guide/). Would be helpful to have this linked [here as well](https://micronaut-projects.github.io/micronaut-mongodb/latest/guide/#testing).

**Comment by alvarosanchez** [comment]
You could do:

```groovy
        given:
        GenericContainer mongo = new GenericContainer("mongo:4.0")
        mongo.start()

        when:
        ApplicationContext applicationContext = ApplicationContext.run(
                (MongoSettings.MONGODB_URI): "mongodb://${mongo.containerIpAddress}:${mongo.getMappedPort(27017)}"
        )

        //...
```

**Comment by alvarosanchez** [comment]
PRs welcomed.

**Comment by brianwyka** [comment]
@alvarosanchez, you can assign me.

**Comment by anandjaisy** [comment]
> ```groovy
> 27017
> ```



```
@BeforeAll
    @DisplayName("Initial data setup")
    void initialDataSetup() {
        mongoDBContainer.start();
        rabbitMQContainer.start();
        applicationContext = ApplicationContext.run(
                Map.of("mongodb.uri", String.format("mongodb://%s:%s", mongoDBContainer.getContainerIpAddress(), mongoDBContainer.getMappedPort(27017)))
        );
    }
```
The `mongoDBContainer.getContainerIpAddress() `is localhost for me, the mongoDBContainer is picking the ip address of the docker image not the test container for me

**Comment by graemerocher** [comment]
Done in https://guides.micronaut.io/latest/micronaut-data-mongodb-synchronous-gradle-java.html
